export const CLEAR_COLLECTION_ENTRY = "CLEAR_COLLECTION_ENTRY";
export const CLEAR_DETAIL_ENTRY = "CLEAR_DETAIL_ENTRY";
export const COLLECTION_ENTRY = "COLLECTION_ENTRY";
export const DETAIL_ENTRY = "DETAIL_ENTRY";
export const ENTRIES = "ENTRIES";
export const ENTRIES_FILTER = "ENTRIES_FILTER";
